version: '3'

services:
  nginx:
    restart: always
    image: nginx:latest
    expose:
      - 9000
    ports:
      - "9000:9000"
    volumes:
      - static:/app/static
      - media:/app/media
      - ./logs:/app/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    links:
      - app:app

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432

  redis:
    image: redis:alpine

  app:
    build: .
    volumes:
      - .:/app
      - static:/app/static_root
      - media:/app/media
    command: >
        bash -c "python3.6 manage.py migrate
        && python3.6 manage.py collectstatic --noinput
        && python3.6 manage.py compilemessages
        && gunicorn -c gunicorn.py supermarket.wsgi -w 2 -b :9991"

    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A supermarket worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
    pgdata:
        driver: local
    static:
    media:
